opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - multiline_arguments
  - switch_case_alignment

disabled_rules:
  - explicit_self
  - identifier_name
  - file_header
  - missing_docs
  - blanket_disable_command
  - trailing_comma

force_cast: warning
force_try: warning

line_length:
  warning: 120
  error: 140

cyclomatic_complexity:
  warning: 15
  error: 25

excluded:
  - .build
  - bin
