#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

source "$ROOT_DIR/version.env"

VERSION="${INOTES_VERSION:-$MARKETING_VERSION}"

cat > "$ROOT_DIR/Sources/inotes/Version.swift" <<EOF
// Auto-generated by scripts/generate-version.sh — do not edit.
let inotesVersion = "$VERSION"
EOF
